### ISSUE TITLE
Add support for input tag

### ISSUE THREAD

**Issue by phdesign** [okcoker/taggle.js#130]
Hi, 

Thanks for your effort into a clean, simple library. Can I ask what was the reasoning for the decision to use a div tag for markup? Wouldn't an input tag be more semantically correct? And if it contained a comma separated list of values then the user couldn't still submit the form even if taggle didn't load for some reason.

Thanks.

**Comment by okcoker** [comment]
> Thanks for your effort into a clean, simple library. 

🙏 

> Can I ask what was the reasoning for the decision to use a div tag for markup? Wouldn't an input tag be more semantically correct? 

The div is just the container around the input and tags. Are you asking why its a `div` instead of a `textarea` or maybe an `input`? If the container div was a textarea or something similar, then as soon as a user taps on the box, the cursor is placed in the top right of the textarea/input. Sure you can use padding to adjust that but how would you solve for multiple lines of tags? Instead the input is just hidden (so semantically you're still typing in an input) and the tags are added as little containers of `input[type="hidden"]` (semantically what you need for form submission). If you put all of this inside of a `<form>` element which is still semantically valid, and press submit. The form submit body should be as expected. Does that answer the question?

> And if it contained a comma separated list of values then the user couldn't still submit the form even if taggle didn't load for some reason. 

Not sure what you mean here. Do you mean if JavaScript isn't loaded or fails to load? In that case you would never be able to add tags in the first place right?

**Comment by phdesign** [comment]
Your interpretation is correct, I meant why not allow an input as the
container element (I did try this and it didn’t work).

I’ve seen similar libraries will clone the original input element, and use
resize the clone to sit next to the tag items.

My reasoning for wanting an input element is that it’s kind of correct,
even if the JavaScript doesn’t load.

Happy for you to close this issue if it doesn’t align with your roadmap,
just wanted to put it out there.
