### ISSUE TITLE
only work with div tag.

### ISSUE THREAD

**Issue by KianSabzi** [okcoker/taggle.js#145]
hi dear.
my problem is I need to insert and also load tags from database in input tag.
is there any way for that?
```


<input id="test" class="form-contorl"/>

<script type="text/javascript">
        new Taggle("test", {
            tags: ['These', 'are', 'prefilled', 'tags']
        });
    </script>
```

**Comment by okcoker** [comment]
Taggle creates an input element and currently does not accept an existing input tag.

You should still be able to load tags from a database and put them in just fine though. If your input is part of a form, just put the div container that you're initializing Taggle with, inside the form instead of your input tag
