### ISSUE TITLE
How are tags sent to the server?

### ISSUE THREAD

**Issue by NorteX-dev** [okcoker/taggle.js#151]
If I have a form, which POSTs the data to a server, how will the tags look? Will it be an array (["tag1", "tag2", "tag3"]), a string ("tag1, tag2, tag3"), or even something else, like an Object?
It claims to be a form-friendly module, so I assume that it should be sending *something*.
I know this is not the perfect place to ask this question, but the only place that I will get an informative answer.

**Comment by okcoker** [comment]
Hi @NorteX-dev this lib doesn't send or make POST requests. That's up to you in how you want to do that (normal form post, axios, fetch, etc).

Each tag contains a hidden input with the name of your choice (defaults to [`taggles[]`](https://github.com/okcoker/taggle.js/blob/f132f24a82ca5c7fbfcd895721b16ffba403849f/src/taggle.js#L99)).

So if your Taggle container is inside a form, you can get the values of the the tags using `e.target['taggles[]']` within your form submit handler. 

Otherwise you can use the Taggle API like `taggle.getTags().values` which is an array and send the data to your server like that.

**Comment by NorteX-dev** [comment]
Hi. Thanks for getting back to me.
If you could provide me an example of sending data from Taggle to a server, together with other fields (text boxes, checkboxes etc.), I would be grateful. It's worth noting that I try to minimalize any client-sided JS.

**Comment by NorteX-dev** [comment]
Also, I don't have a form submit handler. I just have a button, but I guess it wouldn't be a problem to change it.

**Comment by okcoker** [comment]
> If you could provide me an example of sending data from Taggle to a server, together with other fields (text boxes, checkboxes etc.), I would be grateful. It's worth noting that I try to minimalize any client-sided JS.

This is super specific to your app so I wouldn't be able to do this for you if you're not already sending form data.

**Comment by NorteX-dev** [comment]
Ok, well, thanks for help anyway.
