### ISSUE TITLE
2 tags (1 incorrect) being added when using jquery ui autocomplete and autoFocus=true

### ISSUE THREAD

**Issue by facultymatt** [okcoker/taggle.js#55]
When using jquery-ui with taggle, if the autoFocus=true then bad things happen. The autoFocus option automatically selects the first item in the list as the user types in tags. If the user then presses the ENTER key the item is added as a tag. The problem is that its added twice - once by the `select` callback on autocomplete (expected behavior) and an extra time by the taggle plugin (unexpected behavior). 

For example if you have tags `cats, dogs, fish` and the user searches for `ca` with autoFocus=true then `cats` will be highlighted. Upon pressing ENTER, `cats` AND `ca` are added as tags.

**Comment by okcoker** [comment]
Can you provide a jsfiddle with the issue?

**Comment by okcoker** [comment]
This is mostly jQuery specific. You basically want to hand over control to the autocomplete plugin, so in that case you can add the tags programmatically in the select function. The only caveat is that you have to add a fake `submitKey` value [like so](https://jsfiddle.net/okcoker/x83tmoyv/).

I'll update library so you can provide an empty array instead of passing `[-1]` but for now, that looks closer to what you wanted.
