### ISSUE TITLE
preserveCase creates loophole where duplicate tags can still be created

### ISSUE THREAD

**Issue by ndimatteo** [okcoker/taggle.js#60]
When using ```preserveCase: true``` (which is preferred in my instance) the duplicate tag feature fails. While it will still disable creating tags spelled the same, it now only considers tags spelled with the **same casing** as a duplicate. This is problematic as now people can do this:

```Tag, tag, tAg, taG```

**Comment by webchaz** [comment]
This would be great.

**Comment by okcoker** [comment]
Hmm this an interesting issue because if you want to `preserveCase`, technically `Tag` is different than `taG` so it should not be considered a duplicate in my mind (because you're being case sensitive). I could see this being a problem in your instance though. The question is more, how would we implement this in a clean way that works both ways because I still think the current implementation makes sense.

I don't necessarily think we should change the way it works currently as I can see that being somewhat of a breaking change. If we changed the way it works it would have to wait until a 2.0 release. I'm open to suggestions of how to handle this though.

**Comment by ndimatteo** [comment]
@okcoker What if you just added an additional option for ```allowDuplicates```? Basically in addition to ```true```/```false```, you could also set it to ```'strict'``` and then this would simply run it through a ```RegExp``` instead of a simple ```.indexof()```

You can see an example of the difference here: http://codepen.io/ndimatteo/pen/KrvyGX

I imagine this would be pretty easy to add in around line #498: https://github.com/okcoker/taggle.js/blob/master/src/taggle.js#L498

**Comment by okcoker** [comment]
I think if this ever were a thing, I'd rather you pass the regular expression as the actual option. But I think you can use the `beforeTagAdd` option to do your regex check anyway.
