### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by marcelaraujo** [okcoker/taggle.js#65]
Hi

It should have a destroy method to be able remove the entire component.

Thanks

**Comment by okcoker** [comment]
Can't you just remove the container?

```js
container.parentNode.removeChild(container);
```

**Comment by marcelaraujo** [comment]
And about attached events? Remove the node will generate memory leaks, right?

**Comment by marcelaraujo** [comment]
I solved extending your component BTW, I'd appreciate see this on your library.

I will create a PR :)

**Comment by okcoker** [comment]
It would create memory leaks if there are references to the tags after the container is removed. Otherwise they would be garbage collected as usual. I'm just curious as to what the `destroy` method would actually do because `destroy` could do as little as removing the event listeners and maybe the input, or as far as removing the whole container.
